name: Run Clang Format Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  run-test:
    name: Verify code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run clang-format
        run: >
          clang-format --dry-run -Werror 
          include/bitset.h source/bitset.c 
          include/affine_background.h source/affine_background.c 
          include/audio_utils.h source/audio_utils.c 
          include/graphic_utils.h source/graphic_utils.c 
          include/util.h source/util.c
          include/pool.h source/pool.c
          include/card.h source/card.c 
          include/game.h source/game.c 
          include/hand_analysis.h source/hand_analysis.c 
          include/list.h source/list.c
          include/sprite.h source/sprite.c 
          include/splash_screen.h source/splash_screen.c 
          include/blind.h source/blind.c
        # Currently contains only the code that has been formatted to conform
        # When all existing code conforms, change to this:
        # run: clang-format --dry-run -Werror include/*.h source/*.c
